[tool.poetry]
name = "uptrader-test-task"
version = "0.1.0"
description = ""
authors = ["vispar <layred.dota2@mail.ru>"]

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.1.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
